### ISSUE TITLE
Creación del mapa interactivo con Google Map API y TypeScript

### ISSUE THREAD

**Issue by iimxinn** [Arquisoft/lomap_es5b#22]
Hay alguna complicaciones ya que no se me muestra en sí el mapa pero sí el mensaje. 
La API de google está bien importada. 
Mirar que es lo que está mal.
Primer commit hecho a la rama de xin--branch

**Comment by UO271572** [comment]
Le echare un ojo en los proximos dias si no se ha solucionado.

**Comment by iimxinn** [comment]
Resuelto, al final resultó más sencillo hacerlo con MapBox en vez de Google Amps API. Importante cambiar en la documentación el cambio que hemos realizado.
